# Jinix Jupiter HV8 Category-7 physical 2D graphics diagnostic.
#
# Application origin: 0x00000400.
#
# This program:
#   1. writes the exact four-tile HV8 reference tile set;
#   2. writes the exact 40x30 reference tilemap;
#   3. starts the production Jupiter 2D GPU;
#   4. waits for GPU DONE;
#   5. configures production 320x240 framebuffer scanout;
#   6. clears UNDERFLOW while disabled;
#   7. enables scanout;
#   8. halts.
#
# The CPU NEVER fills or modifies the framebuffer.
# All framebuffer pixels must be generated by jupiter_gpu_2d.
#
# Memory:
#   framebuffer = 0x10000000
#   tilemap     = 0x10030000
#   tile data   = 0x10032000
#
# GPU:
#   MMIO base   = 0x00001100
#   MAP_SIZE    = 0x00001E28 = 40 x 30 tiles
#
# Display:
#   MMIO base   = 0x00001180
#   DISPLAY_SIZE= 0x00F00140 = 320 x 240

# ------------------------------------------------------------
# r1 = 0x10000000 framebuffer base.
# 4096 << 16 = 0x10000000.
# ------------------------------------------------------------

ADDI r1, r0, 4096

ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1

ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1

ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1

ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1
ADD r1, r1, r1

# ------------------------------------------------------------
# r2 = 0x10030000 tilemap.
# ------------------------------------------------------------

ADDI r4, r0, 4096

ADD r4, r4, r4
ADD r4, r4, r4
ADD r4, r4, r4
ADD r4, r4, r4

ADD r5, r4, r4
ADD r5, r5, r4

ADD r2, r1, r5

# ------------------------------------------------------------
# r3 = 0x10032000 tile data.
# ------------------------------------------------------------

ADDI r4, r0, 4096
ADD  r4, r4, r4
ADD  r3, r2, r4

# ------------------------------------------------------------
# Exact RGB565 16-bit values.
#
# r10 = red     F800
# r11 = green   07E0
# r12 = blue    001F
# r16 = white   FFFF
# r17 = yellow  FFE0
# r18 = cyan    07FF
# r19 = magenta F81F
# ------------------------------------------------------------

ADDI r10, r0, 31

ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10
ADD r10, r10, r10

ADDI r11, r0, 63

ADD r11, r11, r11
ADD r11, r11, r11
ADD r11, r11, r11
ADD r11, r11, r11
ADD r11, r11, r11

ADDI r12, r0, 31

ADD r16, r10, r11
ADD r16, r16, r12

ADD r17, r10, r11
ADD r18, r11, r12
ADD r19, r10, r12

# ------------------------------------------------------------
# Duplicate each RGB565 value into both halfwords.
#
# r13 = F800F800
# r14 = 07E007E0
# r15 = 001F001F
# r20 = FFFFFFFF
# r21 = FFE0FFE0
# r22 = 07FF07FF
# r23 = F81FF81F
# ------------------------------------------------------------

ADD  r13, r10, r0
ADDI r4, r0, 16

hv8_shift_red:
ADD  r13, r13, r13
ADDI r4, r4, -1
BNE  r4, r0, hv8_shift_red

ADD r13, r13, r10

ADD  r14, r11, r0
ADDI r4, r0, 16

hv8_shift_green:
ADD  r14, r14, r14
ADDI r4, r4, -1
BNE  r4, r0, hv8_shift_green

ADD r14, r14, r11

ADD  r15, r12, r0
ADDI r4, r0, 16

hv8_shift_blue:
ADD  r15, r15, r15
ADDI r4, r4, -1
BNE  r4, r0, hv8_shift_blue

ADD r15, r15, r12

ADD  r20, r16, r0
ADDI r4, r0, 16

hv8_shift_white:
ADD  r20, r20, r20
ADDI r4, r4, -1
BNE  r4, r0, hv8_shift_white

ADD r20, r20, r16

ADD  r21, r17, r0
ADDI r4, r0, 16

hv8_shift_yellow:
ADD  r21, r21, r21
ADDI r4, r4, -1
BNE  r4, r0, hv8_shift_yellow

ADD r21, r21, r17

ADD  r22, r18, r0
ADDI r4, r0, 16

hv8_shift_cyan:
ADD  r22, r22, r22
ADDI r4, r4, -1
BNE  r4, r0, hv8_shift_cyan

ADD r22, r22, r18

ADD  r23, r19, r0
ADDI r4, r0, 16

hv8_shift_magenta:
ADD  r23, r23, r23
ADDI r4, r4, -1
BNE  r4, r0, hv8_shift_magenta

ADD r23, r23, r19

# ------------------------------------------------------------
# Exact tile-data image.
#
# Tile 0: 32 x F800F800
# Tile 1: 32 x 07E007E0
# Tile 2: 32 x 001F001F
# Tile 3:
#   top four rows    = WWWW YYYY
#   bottom four rows = CCCC MMMM
# ------------------------------------------------------------

ADD  r24, r3, r0
ADDI r25, r0, 32

hv8_tile0_loop:
STW  r13, r24, 0
ADDI r24, r24, 4
ADDI r25, r25, -1
BNE  r25, r0, hv8_tile0_loop

ADDI r25, r0, 32

hv8_tile1_loop:
STW  r14, r24, 0
ADDI r24, r24, 4
ADDI r25, r25, -1
BNE  r25, r0, hv8_tile1_loop

ADDI r25, r0, 32

hv8_tile2_loop:
STW  r15, r24, 0
ADDI r24, r24, 4
ADDI r25, r25, -1
BNE  r25, r0, hv8_tile2_loop

ADDI r25, r0, 4

hv8_tile3_top_loop:
STW  r20, r24, 0
STW  r20, r24, 4
STW  r21, r24, 8
STW  r21, r24, 12
ADDI r24, r24, 16
ADDI r25, r25, -1
BNE  r25, r0, hv8_tile3_top_loop

ADDI r25, r0, 4

hv8_tile3_bottom_loop:
STW  r22, r24, 0
STW  r22, r24, 4
STW  r23, r24, 8
STW  r23, r24, 12
ADDI r24, r24, 16
ADDI r25, r25, -1
BNE  r25, r0, hv8_tile3_bottom_loop

# ------------------------------------------------------------
# Initial complete 40x30 macroblock tilemap:
#
# tile = ((tx / 5) + (ty / 5)) mod 3
#
# Six 5-row macroblock bands.
# Eight 5-column macroblocks per band.
# ------------------------------------------------------------

ADD  r4, r2, r0
ADDI r5, r0, 6
ADDI r6, r0, 0
ADDI r7, r0, 3

hv8_tm_blockrow:
ADDI r8, r0, 8
ADD  r9, r6, r0

hv8_tm_block:
ADD  r24, r4, r0
ADDI r25, r0, 5

hv8_tm_block_row:
STW r9, r24, 0
STW r9, r24, 4
STW r9, r24, 8
STW r9, r24, 12
STW r9, r24, 16

ADDI r24, r24, 160
ADDI r25, r25, -1
BNE  r25, r0, hv8_tm_block_row

ADDI r4, r4, 20

ADDI r9, r9, 1
BNE  r9, r7, hv8_tm_color_ok
ADDI r9, r0, 0

hv8_tm_color_ok:
ADDI r8, r8, -1
BNE  r8, r0, hv8_tm_block

# r4 advanced 160 bytes while visiting eight horizontal
# macroblocks. Advance another 640 bytes to move down five
# complete 160-byte tilemap rows.

ADDI r4, r4, 640

ADDI r6, r6, 1
BNE  r6, r7, hv8_tm_start_color_ok
ADDI r6, r0, 0

hv8_tm_start_color_ok:
ADDI r5, r5, -1
BNE  r5, r0, hv8_tm_blockrow

# ------------------------------------------------------------
# Outer one-tile-wide orientation border.
# Tile index 3.
# ------------------------------------------------------------

ADD  r24, r2, r0
ADDI r25, r0, 40

hv8_tm_top_border:
STW  r7, r24, 0
ADDI r24, r24, 4
ADDI r25, r25, -1
BNE  r25, r0, hv8_tm_top_border

ADDI r24, r2, 4640
ADDI r25, r0, 40

hv8_tm_bottom_border:
STW  r7, r24, 0
ADDI r24, r24, 4
ADDI r25, r25, -1
BNE  r25, r0, hv8_tm_bottom_border

ADDI r24, r2, 160
ADDI r25, r0, 28

hv8_tm_side_borders:
STW  r7, r24, 0
STW  r7, r24, 156
ADDI r24, r24, 160
ADDI r25, r25, -1
BNE  r25, r0, hv8_tm_side_borders

# ------------------------------------------------------------
# 4x4 center orientation marker.
#
# tx = 18..21
# ty = 13..16
#
# byte offset:
#   13 * 160 + 18 * 4 = 2152
# ------------------------------------------------------------

ADDI r24, r2, 2152
ADDI r25, r0, 4

hv8_tm_center:
STW  r7, r24, 0
STW  r7, r24, 4
STW  r7, r24, 8
STW  r7, r24, 12
ADDI r24, r24, 160
ADDI r25, r25, -1
BNE  r25, r0, hv8_tm_center

# ------------------------------------------------------------
# Production 2D GPU.
#
# 0x1108 TILEMAP_BASE
# 0x110C TILEDATA_BASE
# 0x1110 FRAMEBUFFER_BASE
# 0x1114 MAP_SIZE
# 0x1100 CONTROL.START
# 0x1104 STATUS
# ------------------------------------------------------------

ADDI r27, r0, 4352

STW r2, r27, 8
STW r3, r27, 12
STW r1, r27, 16

ADDI r28, r0, 7720
STW  r28, r27, 20

ADDI r28, r0, 1
STW  r28, r27, 0

ADDI r29, r0, 2

hv8_gpu_done_poll:
LDW r26, r27, 4
BNE r26, r29, hv8_gpu_done_poll

# ------------------------------------------------------------
# Production display scanout.
#
# 0x1188 DISPLAY_BASE
# 0x118C DISPLAY_SIZE
# 0x1180 DISPLAY_CONTROL
#
# Write CONTROL=2 first:
#   ENABLE=0
#   CLEAR_UNDERFLOW=1
#
# Then CONTROL=1:
#   ENABLE=1
# ------------------------------------------------------------

ADDI r27, r0, 4480

STW r1, r27, 8

ADDI r28, r0, 240

ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28

ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28

ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28

ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28
ADD r28, r28, r28

ADDI r28, r28, 320
STW  r28, r27, 12

ADDI r28, r0, 2
STW  r28, r27, 0

ADDI r28, r0, 1
STW  r28, r27, 0

HALT
